### ISSUE TITLE
multiple rlib candidates for `aoc_main` found

### ISSUE THREAD

**Issue by jhscheer** [remi-dupre/aoc#16]
I want to use the benchmarks, but I don't understand how the criterion toggle is supposed to work.
After moving `example.rs` to a `main.rs` "cargo run" works just fine.
However, if I add 
```toml
[dependencies]
aoc-main = { version = "*", features = ["bench"] }
```
to `Cargo.toml` I get the above error.
